version: 2.1

orbs:
 android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android

    steps:
      - checkout
      - run: 
          command: echo $GOOGLE_SERVICES_JSON | base64 --decode --ignore-garbage > ./app/google-services.json
      - run:
          command: ./gradlew assembleDebug
      - run:
          command: ./gradlew testDebugUnitTest
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/outputs/apk/debug/app-debug.apk
          destination: app-debug.apk
          
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: 
                - feature/qiita_10_sub/circleci
                - /^feature/qiita_1[1-9]/