version: 2.1

orbs:
 android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android

    steps:
      - checkout
      - run:
          command: ./gradlew assembleDebug
      - run:
          command: ./gradlew testDebugUnitTest

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: feature/qiita_10_c 

