name: Android CI

on:
  push:
    branches-ignore:
      - 'master'
      - 'feature/qiita_10_**'

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Slack notification
      uses: homoluctus/slatify@master
      with:
#         type: ${{ job.status }}
        type: failure
        job_name: '*Build and DebugCheck*'
        channel: '#general'
        url: ${{ secrets.SLACK_WEBHOOK_URL }}
