name: Android CI

on:
  push:
    branches-ignore:
      - 'master'
      - 'feature/qiita_10_**'

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Build with Gradle
      run: ./gradlew assembleDebug
      
    - name: Check
      if: success()
      run: ./gradlew lint testDebugUnitTest
      
    - name: Android Emulator Runner
      if: always()
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 28
        profile: Nexus 6
        script: ./gradlew connectedCheck
        
    - name: Archive results
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: test-reports
        path: app/build/reports

    - name: Archive Debug Apk
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: debugApk
        path: app/build/outputs/apk/debug/app-debug.apk
