name: Android CI

on:
  push:
    paths-ignore:
      - '**.md'
    branches-ignore:
      - master
      - 'feature/qiita_10_sub/**'

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  build:
    runs-on: macOS-latest
    needs: prepare

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: copy google-service
      env:
          GOOGLE_SERVICE: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $GOOGLE_SERVICE | base64 --decode --ignore-garbage > ./app/google-services.json
    - name: Build with Gradle
      run: ./gradlew assemble
      
    - name: Archive Debug Apk
      if: success()
      uses: actions/upload-artifact@v1
      with:
        name: debugApk
        path: app/build/outputs/apk/debug/app-debug.apk

#     - name: Sign Release Apk
#       if: success()
#       uses: r0adkll/sign-android-release@v1
#       with:
#         releaseDirectory: app/build/outputs/apk/release
#         signingKeyBase64: ${{ secrets.SIGNING_KEY }}
#         alias: ${{ secrets.ALIAS }}
#         keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
#         keyPassword: ${{ secrets.KEY_PASSWORD }}
#       id: sign-apk 
#   
#     - name: Archive Release Apk
#       if: success()
#       uses: actions/upload-artifact@v1
#       with:
#         name: releaseApk
#         path: ${{ steps.sign-apk.outputs.signedReleaseFile }}

    - name: Check
      if: success()
      run: ./gradlew lint testDebugUnitTest
      
    - name: Android Emulator Runner
      if: always()
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 28
        profile: Nexus 6
        script: ./gradlew connectedCheck
        
    - name: Archive results
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: test-reports
        path: app/build/reports

    - name: Slack notification
      if: always()
      uses: homoluctus/slatify@master
      with:
        type: ${{ job.status }}
        job_name: '*Build and DebugCheck*'
        channel: '#qiitapedometersample'
        commit: true
        token: ${{ secrets.GITHUB_TOKEN }}
        url: ${{ secrets.SLACK_WEBHOOK_URL }}
