name: SlackNotify

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Slack notification
      uses: homoluctus/slatify@master
      with:
        type: ${{ job.status }}
        job_name: '*Build and DebugCheckk*'
        channel: '#general'
        url: ${{ secrets.SLACK_WEBHOOK_URL }}
