name: SlackNotify

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Slack notification
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_CHANNEL: general # Optional. (defaults to webhook)
      uses: bryan-nice/slack-notification@master
      with:
        args: 'Github Actionsのワークフローが完了しました。' 
    
    
